"use client";
// import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div className="container nav__container">
            <Link href="/homePage">
              <Image
                src="/logo.png"
                width={100}
                height={100}
                alt="Picture of the author"
              />
            </Link>
            <a href=""></a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
